pipeline{
//  agent{
//    docker{
//      image 'python:3.7.2'
//      args '-u root:sudo -v $HOME/workspace/instavote_vote_vote_Jenkinsfile:/instavote_vote_vote_Jenkinsfile'
//    }
//  }
  agent any

  stages{
    stage('docker-package'){
        agent any
        steps{
            echo 'Packaging worker app with docker'
            script{
                docker.withRegistry('', 'dockerlogin') {
                    def workerImage = docker.build("khaerulanam/vote:v${env.BUILD_ID}", "./vote")
                    workerImage.push()
                    workerImage.push("latest")
                }
            }
        }
    }

}
    post{
      always {
        echo 'Building multibranch pipeline for worker is completed..'
      }
      failure {
          slackSend (channel: "jenkins-cicd", message: "Build Failed Quiz 8.1 (2) by ANAM - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      success {
          slackSend (channel: "jenkins-cicd", message: "Build Succeeded Quiz 8.1 (2) by ANAM - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
    }

  }
